### ISSUE TITLE
Make use of treeherder-client 3.0.0's connection pooling

### ISSUE THREAD

**Issue by edmorley** [mozilla/arewefastyet#105]
treeherder-client 3.0.0 now re-uses a requests session for the duration of that TreeherderClient instance.

If arewefastyet updated to 3.0.0 and refactored slightly, so that it re-used the same `TreeherderClient` for each build submission, you'd get a perf improvement from the HTTP keep-alives.

See here for more details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1286240

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
