### ISSUE TITLE
WebVR : Enable VR Mode for Aquarium

### ISSUE THREAD

**Issue by shaoboyan** [mozilla/arewefastyet#125]
Currently, WebVR 1.1 is supported by lots of browsers, like firefox, chrome, etc. However , there isn't any ready benchmark or workload for  browser based VR experience.
Since Aquarium is one of the famous benchmark of WebGL, we'd like to align it as the benchmark for browser based VR experience, too.
I've worked out the prototype of VR Mode for Aquarium now. And if you agree, I''m very happy to contribute this !

**Comment by bnjbvr** [comment]
Hi! Thanks for the proposition, it sounds like a good idea for a promising API!

I have contacted our VR stakeholders at Mozilla to see if they would be interested in having such a benchmark running in arewefastyet, unless there are other websites to track WebVR performance. I'll get back to you as soon as I hear back from them.

**Comment by shaoboyan** [comment]
@bnjbvr  thx for responding ! I've moved this issue to WebGL Sample repo, it is the aquarium sample upstream. The new issue link here: https://github.com/WebGLSamples/WebGLSamples.github.io/issues/8
and the proposed patch here : https://github.com/WebGLSamples/WebGLSamples.github.io/pull/9

**Comment by bnjbvr** [comment]
Thanks for letting me know!
