### ISSUE TITLE
[Website] Usability issue for folding menu

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/arewefastyet#127]
I can not see the complete "Breakdown" menus if I have the "Machines » " or "[Show obsolete modes]" menus already expanded, in 1366 x 768 px. The left side should be can scroll (may have difficulty for implement), or automatically folding another menu when expanding a menu.

**Comment by bnjbvr** [comment]
Good catch, that is a problem indeed. My CSS-foo is very bad, so I would welcome any pull request here :)

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
