### ISSUE TITLE
Add support for m-c PGO builds

### ISSUE THREAD

**Issue by armenzg** [mozilla/arewefastyet#130]
We're currently running against mozilla-inbound opt builds.
Ideally we should run against PGO builds since it is closer to what our users.

If it is easy to switch over and doesn't cause any issues let's give it a shot.
It will probably create few alerts when switching over.

**Comment by armenzg** [comment]
It might require #128 to be fixed this.

**Comment by h4writer** [comment]
I used to scrape PGO builds from inbound. (see
http://arewefastyet.com/#machine=17)
It gives some extra information and is closer to what our users use.
BUT it also has some drawbacks.
1) Unrelated changes can throw off the PGO optimizations and as a result
give big improvements/regressions while not being actionable to fix them.
2)  One of the main things AWFY does is giving a regression range over who
caused a regression. Since PGO builds happen less often that regression
range is too long to be useful.

As a result PGO builds are good for having "correct" results, but doesn't
help with tracking regressions.

**Comment by bnjbvr** [comment]
A satisfying alternative would be to use PGO builds for the Quantum machine, and normal builds for the other machines; so the Windows machine which also runs Speedometer would help tracking regressions, while the Quantum machine would show raw perf. How does it sound?

**Comment by armenzg** [comment]
@h4writer FYI we've noticed that the TaskCluster CI team is producing PGO builds on a per-push schedule rather than periodically (like on the Buildbot CI land).

> 1) Unrelated changes can throw off the PGO optimizations and as a result give big
> improvements/regressions while not being actionable to fix them.
Is this also true for Talos? Should we not run Talos against PGO builds?

**Comment by armenzg** [comment]
@bnjbvr I won't be adding the machine I have to the automation since I will leave that to bc setting up the MTV lab.

In this PR I would like to add mozilla-central PGO builds to machine 36 (only speedometer for now to not reduce how much it can cover on a day).

What changes would be required?

I will be back on Monday (Friday off). I won't be at the all hands.

**Comment by bnjbvr** [comment]
Great! Changes would be needed in download.py / url_creator.py only. You'd need to introduce a new option for downloading a mozilla-central-pgo build, then go down the rabbit hole to find what to change in these two files. Some Treeherder scraping might be involved, unless we decide to fix #128 at the same time.

**Comment by armenzg** [comment]
Feel free to assign this to me.

**Comment by armenzg** [comment]
https://github.com/mozilla/arewefastyet/pull/134

**Comment by armenzg** [comment]
We can now download PGO builds with --buildtype pgo

**Comment by armenzg** [comment]
Let me keep this open to also schedule the mc PGO tasks

**Comment by armenzg** [comment]
I've added a control task which will not submit anything until I figure out proper reporting.
For now, I've made it to be schedule every 5 minutes (to get it to run) but I will then bump it to once a day.

> python download.py --repo mozilla-central -o ~/repos/mozilla-central-pgo/ -c 64bit -b pgo
> python execute.py -s print -b remote.speedometer-misc -e ~/repos/mozilla-central-pgo/ -c default

**Comment by armenzg** [comment]
I've inserted an awfy_mode:
```mysql
INSERT INTO `awfy_mode` (`id`, `vendor_id`, `mode`, `name`, `color`, `level`) VALUES (NULL, '5', 'firefox_pgo', 'Ion PGO', '#FF8800', '10'); 
```

Here are the relevant fields of the control_task (and created a control_task_queue):
control_unit_id: "9"
machine_id: "36"
mode_id: "0"
delay: "86400"
task: 
> "python download.py --repo mozilla-central -o ~/repos/mozilla-central-pgo/ -c 64bit -b pgo
> python submitter.py -c -m 36 -o /tmp/submitter_id
> python execute.py -s remote --submitter-session /tmp/submitter_id -b remote.speedometer-misc -e ~/repos/mozilla-central-pgo/ -c default --submitter-mode=""firefox,default:firefox_pgo""
> python submitter.py -f -s /tmp/submitter_id"

**Comment by armenzg** [comment]
and it works!
https://arewefastyet.com/#machine=36&view=single&suite=speedometer-misc&subtest=score

I will send an email to stakeholders and see what is next.
