### ISSUE TITLE
Edge/speedometer generated results file is truncated

### ISSUE THREAD

**Issue by armenzg** [mozilla/arewefastyet#137]
executors.py expects a results file, however, it shows up as truncated.
I've seen two of these truncated files and they both have the exact same size (2866 bytes)
I have not been able to figure out what generates this file.

I've executed the harness like this:
> python execute.py -s print -b remote.speedometer-misc -e ~/repos/edge/ -c default

Output of the script:
> EXECUTE -- Exception: ValueError('Unterminated string starting at: line 1 column 2856 (char 2855)',)
> Traceback (most recent call last):
>   File "execute.py", line 149, in <module>
>     results = executor.run(benchmark, config)
>   File "/home/rwood/arewefastyet/slave/executors.py", line 61, in run
>     results = json.loads(fp.read())
>   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Unterminated string starting at: line 1 column 2856 (char 2855)

Contents of results file:
> {"tests":{"VanillaJS-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":808.8798682112562,"Async":30.90516014713171},"total":839.7850283583879},"CompletingAllItems":{"tests":{"Sync":169.71982091954305,"Async":10.710182096989001},"total":180.43000301653205},"DeletingAllItems":{"tests":{"Sync":142.30009928529103,"Async":1.8402125481759412},"total":144.14031183346697}},"total":1164.3553432083867},"Vanilla-ES2015-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":663.0751304212777,"Async":34.75497183787866},"total":697.8301022591563},"CompletingAllItems":{"tests":{"Sync":135.08516903032796,"Async":17.769805751549484},"total":152.85497478187744},"DeletingItems":{"tests":{"Sync":104.99536853530935,"Async":3.564798479019373},"total":108.56016701432872}},"total":959.2452440553625},"Vanilla-ES2015-Babel-Webpack-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":461.84982961073956,"Async":34.714865188323984},"total":496.56469479906354},"CompletingAllItems":{"tests":{"Sync":113.645178178057,"Async":12.264954766952541},"total":125.91013294500953},"DeletingItems":{"tests":{"Sync":94.04497320747805,"Async":5.125117813282941},"total":99.17009102076099}},"total":721.6449187648341},"React-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":380.119731148915,"Async":33.43017240312656},"total":413.54990355204154},"CompletingAllItems":{"tests":{"Sync":201.89516719139465,"Async":15.670179980723332},"total":217.56534717211798},"DeletingAllItems":{"tests":{"Sync":135.5502354985665,"Async":2.7097588438364255},"total":138.25999434240293}},"total":769.3752450665624},"React-Redux-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":484.2698733781872,"Async":25.110175952991994},"total":509.3800493311792},"CompletingAllItems":{"tests":{"Sync":688.4801329151433,"Async":11.90484825393105},"total":700.3849811690743},"DeletingItems":{"tests":{"Sync":390.8102865876117,"Async":3.289598596437827},"total":394.0998851840495}},"total":1603.864915684303},"EmberJS-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":1884.2402627241535,"Async":31.69534647665205},"total":1915.9356092008056},"CompletingAllItems":{"tests":{"Sync":926.8151778921911,"Async":15.095033559451621},"total":941.9102114516427},"DeletingItems":{"tests":{"Sync":1269.9053781737056,"Async":3.2102386302995},"total":1273.1156168040051}},"total":4130.9614374564535},"BackboneJS-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":190.9298385366037,"Async":45.52488724271461},"total":236.45472577931832},"CompletingAllItems":{"tests":{"Sync":89.81969501026287,"Async":23.260150075670026},"total":113.0798450859329},"DeletingAllItems":{"tests":{"Sync":62.32488007471693,"Async":4.660051345044849},"total":66.98493141976178}},"total":416.519502285013},"AngularJS-TodoMVC":{"tests":{"Adding100Items":{"tests":{"Sync":747.6899209856328,"Async":41.49032896412609},"total":789.180249949759},"Completing

**Comment by bnjbvr** [comment]
Thanks for opening an issue.

The `execute.py` script launches a proxy server (`server.py`) with Popen, but there's no clean way for communication between them. When a benchmark is done executing, it submits results to the server, which then saves the results into a file on disk. A spin loop in the `execute.py` checks every 10 seconds that the file is available; if it's not, it will wait a bit.

A few things could happen here:
- race condition: execute tries to read the file before it's entirely written
- the server doesn't flush the file write on disk
- results are partially not saved because of a possible too-long-query issue (that's #132)

I'd like to overhaul the cross-process communication entirely; we could kill many birds with that stone. In the meanwhile, I'll try to investigate this for a short workaround.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
