### ISSUE TITLE
Switch Ion PGO from mozilla-central PGO builds to the nightly build

### ISSUE THREAD

**Issue by armenzg** [mozilla/arewefastyet#138]
We're currently testing the m-c PGO build instead of the nightly build.
I will fix this.

**Comment by armenzg** [comment]
Once the PR lands I can update the control task to start using nightly builds.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
