### ISSUE TITLE
Run speedometer with mozilla-beta and mozilla-release

### ISSUE THREAD

**Issue by armenzg** [mozilla/arewefastyet#139]
I'm thinking of calling them:

- Firefox ION (mozilla-beta)
- Firefox ION (mozilla-release)

I would like to schedule the beta every 48-72 hours while mozilla-release should be scheduled once a week.

**Comment by armenzg** [comment]
We could schedule mozilla-release every several weeks, however, I want to see few data points on the graph (I think it shows up to 4 weeks).

**Comment by bnjbvr** [comment]
Cool. The fixes from yesterday now allow to easily download mozilla beta/release builds on all the platforms, so that's good timing.

**Comment by bnjbvr** [comment]
Note mozilla-beta is now running on some machines on AWFY. mozilla-release is not configured yet, at the moment, since there isn't any big demand about it right now.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
