### ISSUE TITLE
Run Chrome release weekly and Canary daily

### ISSUE THREAD

**Issue by armenzg** [mozilla/arewefastyet#140]
We need to see what it takes to download it.

**Comment by armenzg** [comment]
We currently run *all* benchmarks for Chromium every few hours.
I would like to reduce that to Canary **daily** and Chrome release **weekly**.

Steps needed:
* Add support for Chrome releases
* Verify that we're not downloading Dev builds but Canary ones
* Change commands on the control task

This is only for the Quantum reference laptop.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
