### ISSUE TITLE
Allow to define specific score orderings for sub-benchmarks

### ISSUE THREAD

**Issue by bnjbvr** [mozilla/arewefastyet#142]
The score ordering direction is now defined at the benchmark level. Speedometer2 default ordering is "lower is better", but we'd like the `score` sub-benchmark to be in the reverted direction (higher is better).

I propose the following:
- add a column in the awfy_suite_test table, `better_direction`.
- it could take the following values:
  - `-1` same as the meaning of `better_direction == -1` at the suite level
  - `1` ditto
  - `0` keep the same direction as the suite
- the default value would be `0` (keep same as usual).

**Comment by armenzg** [comment]
👍
