### ISSUE TITLE
Missing changesets in hg changelog

### ISSUE THREAD

**Issue by nbp** [mozilla/arewefastyet#149]
https://arewefastyet.com/#machine=37&view=single&suite=speedometer-misc&subtest=React-Redux-TodoMVC-Adding100Items-sync&start=1500369539&end=1500401500

Taking the changelogs of the lowest and highest (Ion) points gives the following links:
https://hg.mozilla.org/integration/mozilla-inbound/log?rev=38615ea1031444020b37b34a7c759e15a2b2e6bf%3A%3Ab230bd5c696b7e057e76d504a5798af878870220%20and%20!38615ea1031444020b37b34a7c759e15a2b2e6bf (Push 92682 - 92689)
https://hg.mozilla.org/integration/mozilla-inbound/log?rev=4da0547ae82c8b271bb38a9658e6ff25d186e870%3A%3A38615ea1031444020b37b34a7c759e15a2b2e6bf%20and%20!4da0547ae82c8b271bb38a9658e6ff25d186e870 (Push 92669 - 92672)

These changelogs are missing the following commit:
https://hg.mozilla.org/integration/mozilla-inbound/rev/0f61bc51de11 (Push 92674)

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
