### ISSUE TITLE
Delete outlier on destructuring-es6

### ISSUE THREAD

**Issue by evilpie** [mozilla/arewefastyet#152]
The outlier makes 
https://arewefastyet.com/#machine=29&view=single&suite=six-speed&subtest=destructuring-es6 very difficult to read. Can we delete that single data point?

**Comment by bnjbvr** [comment]
I'll do it and document the process.

**Comment by bnjbvr** [comment]
Work done on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1388057
It's done and should appear after the next update of the cached static files, when a new run occurs.
