### ISSUE TITLE
Use requirements files to track Python dependencies

### ISSUE THREAD

**Issue by edmorley** [mozilla/arewefastyet#153]
There doesn't appear to be a requirements file in this repo. 

Instead I see:
```python
try:
    from thclient import TreeherderClient, TreeherderJob, TreeherderJobCollection
except:
    print "run 'sudo pip install treeherder-client' to install the needed libraries"
    exit()
```

This is not ideal, since:
* There's no way to know what package versions are being used in production or to pin to specific versions.
* There is no automated way (eg deploy script) to update the versions by changing a requirements file in the repo (instead someone has to SSH in and manually run pip commands).
* You can't use tools like [pyup](https://pyup.io/) to automate keeping the requirements file up to date.
* Using `sudo` with pip install is almost always the wrong thing to do.

The context for this is that Treeherder occasionally needs to release new treeherder-client versions for changes (or deprecations) being made to the API. Consumers of the API or the client need to stay relatively up to date or risk breakage.

**Comment by bnjbvr** [comment]
Thanks for filing an issue. For what it's worth, I'd like that too, so that we can use `requests` instead of our own HTTP handling.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
