### ISSUE TITLE
Use treeherder-client's add_revision() instead of add_revision_hash()

### ISSUE THREAD

**Issue by edmorley** [mozilla/arewefastyet#154]
Since the latter is deprecated and about to be removed:
https://github.com/mozilla/treeherder/blob/ae033a0ebfab7eebee93eecb33e45ab4c82339c6/treeherder/client/thclient/client.py#L150-L157

Treeherder now supports submitting a job by using just the 40 character revision SHA, without needing the interim step of converting that revision to the 'revision hash'.

To do this:
1) Make sure you are using a recent treeherder-client (I can't tell if you are or not sadly, due to #153)
2) Replace `job.add_revision_hash(self.retrieve_revision_hash())` with `job.add_revision(self.revision)` (here: https://github.com/mozilla/arewefastyet/blob/2696cbea7fbbe50c3a8cbf70a0ac3c70f135852e/treeherder/submission.py#L80)
3) Remove the now unused `retrieve_revision_hash` method (https://github.com/mozilla/arewefastyet/blob/2696cbea7fbbe50c3a8cbf70a0ac3c70f135852e/treeherder/submission.py#L106-L129)

**Comment by bnjbvr** [comment]
Will it break any time soon if we don't make this change?

**Comment by edmorley** [comment]
We were hoping to make this change fairly soon, since this method was deprecated (with log warning) since the treeherder 2.1.0 client release in April 2016.

This is where #153 combined with a service like https://pyup.io really pays off, since keeping up to date with new packages is really easy :-)

**Comment by edmorley** [comment]
I've opened #171 for this.
