### ISSUE TITLE
Fix tests to not use a changeset that will expire in a year

### ISSUE THREAD

**Issue by armenzg** [mozilla/arewefastyet#162]
In order to test the code we've hard-coded a changeset from inbound.
https://github.com/mozilla/arewefastyet/pull/160#discussion_r134002992

The artifacts for this changeset will expire in a year.

The fix is to talk to hg web to gives us some valid changesets or to patch the function to allow any changesets (using mocking).

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
