### ISSUE TITLE
Disable updates & telemetry for Firefox

### ISSUE THREAD

**Issue by digitarald** [mozilla/arewefastyet#164]
There might be some options we should flip to disable telemetry and crash reports, as best practice for automated test machines.

Are they intentionally kept on?

cc @bnjbvr

**Comment by bnjbvr** [comment]
I think there's an intent to use a standard set of prefs that are used in automation, and served through mozprofiles or another Mozilla python package. @bclary might know more.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
