### ISSUE TITLE
Update treeherder-client from 2.0.1 to 4.0.0

### ISSUE THREAD

**Issue by edmorley** [mozilla/arewefastyet#169]
Please can you update [treeherder-client](https://pypi.python.org/pypi/treeherder-client) to the latest release (4.0.0) to pick up changes to which API endpoints are used (the old endpoints will be disabled at some point in the future).

Sadly there isn't a requirements file I can update due to #153 - though I know you're on 2.0.1 from the User Agent I see from the `awfy` Hawk ID in our logs.

The changelog for the 4.0.0 release can be found here (I don't have the others to hand, they are from so long ago):
https://bugzilla.mozilla.org/show_bug.cgi?id=1387711#c2

As part of this, you'll need to fix #154 too.

Many thanks!

**Comment by bnjbvr** [comment]
@edmorley Can you please confirm you see the expected version number in the logs? It should have been updated the way you described in the PR, but better to double-check this.

**Comment by edmorley** [comment]
Looks good to me - thank you!

![awfy-user-agent](https://user-images.githubusercontent.com/501702/30345840-a50556a2-97fe-11e7-871d-da27db13a32a.jpg)
