### ISSUE TITLE
Add Firefox 57 Beta to machine 36's speedometer-misc

### ISSUE THREAD

**Issue by digitarald** [mozilla/arewefastyet#178]
Just want to make sure Beta 57 is tracked on https://arewefastyet.com/#machine=36&view=breakdown&suite=speedometer-misc so we can keep an eye out for possible regressions. It might be covered by the `Firefox Beta (Ion)` entry.

**Comment by bnjbvr** [comment]
Yes: AWFY uses what Treeherder calls "beta", "nightly" etc. to download the browser build it will benchmark, so I expect the move of 57 to beta has just automatically happened and `Firefox Beta (ion)` shows 57. Unless @bclary sees something that I am missing here, I think we can close?

**Comment by bclary** [comment]
Beta should have transitioned from 56 to 57 in the same way that Nightly transitioned from 57 to 58.
