### ISSUE TITLE
JSC is stopping

### ISSUE THREAD

**Issue by Constellation** [mozilla/arewefastyet#182]
It seems that JSC report is stopping from r224142 (http://trac.webkit.org/changeset/224142).
I can help if JSC side work is necessary :)

**Comment by bnjbvr** [comment]
```output was: Can't locate Encode/Locale.pm in @INC (you may need to install the Encode::Locale module)```

Is there a new Perl dependency here?

**Comment by bnjbvr** [comment]
Thanks for the report, btw!

**Comment by Constellation** [comment]
Nice, r224143 includes `Encode/Locale` requirement. I'm not sure whether it is included in standard perl bundle in macOS. Is it included? If it isn't, we should remove this from ToT.

**Comment by bnjbvr** [comment]
Well, we haven't touched the basic configurations of the machine, which is running last MacOS version as far as I know. Should we manually install this perl module? Or will it be removed from the build requirements? (what does ToT mean?)

**Comment by Constellation** [comment]
Could you install `Encode::Locale` and `JSON::PP` manually in the meantime?

**Comment by bnjbvr** [comment]
@bclary Can you have a look, please?

**Comment by bclary** [comment]
awfy-cmp-osx: 10.12.6 updates pending...

Updated port and then installed

p5.24-json
p5.24-encode

*******************************************************************************
Downloading for repository webkit
Traceback (most recent call last):
  File "download.py", line 379, in <module>
    options.cset, options.buildtype)
  File "download.py", line 58, in download_for_repo
    raise Exception("couldn't find the revision.")
Exception: couldn't find the revision.

I'm doing the same for awfy-shells-macpro: 10.12.6 thought it is taking longer. I'll follow up when that completes.

**Comment by bclary** [comment]
completed on awfy-shells-macpro and restarted. @bbouvier: I'll ping you in &pi;

**Comment by bclary** [comment]
Also needed p5.24-encode-locale

**Comment by bnjbvr** [comment]
Looks like it got fixed in the meanwhile by JSC people, since it began to work again on October 31st. Thanks for the report @Constellation and thanks for updating the machine @bclary, this should prevent future issues. Closing.
