### ISSUE TITLE
The judgment criteria for Speedometer and Dromaeo benchmarks are not correct.

### ISSUE THREAD

**Issue by BruceDai** [mozilla/arewefastyet#184]
The unit of test score for Dromaeo benchmark is 'runs/s', and the unit of test score for Speedometer benchmark is 'Runs / Minute', so both the judgment criteria for them should be 'Lower is better: No', not  'Lower is better: Yes'

**Comment by bnjbvr** [comment]
Thanks for the report.

For Dromaeo, if I look at [the score page](https://arewefastyet.com/#machine=35&view=breakdown&suite=dromaeo), it seems that it displays the inverted scale on the Y axis (and it shows "score"), meaning it's already in "higher is better" mode.

Ditto for Speedometer's `score` line (all the other are timings, so for these lower is better).

So I think it is correct as is, unless I miss something else. Does it sound right? Is the inverted Y scale confusing?

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
