### ISSUE TITLE
AWFY does not build new engines from March 31

### ISSUE THREAD

**Issue by Constellation** [mozilla/arewefastyet#196]
Hi,

It seems that AWFY does not build a new engine after March 31.
For example, JSC remains r230100. V8 and SpiderMonkey have the same issue.
Is it a planned maintenance?

**Comment by bnjbvr** [comment]
Ping @bclary.

**Comment by bclary** [comment]
Is this still an issue? There are numerous problems with awfy. If you can be more specific on which machines and tests are not running that would be very helpful.
