### ISSUE TITLE
Question: Webrender

### ISSUE THREAD

**Issue by NiLSPACE** [mozilla/arewefastyet#202]
For a while now the x64 Quantum reference machine has a Firefox with WebRender mode on motionmark[1], but it doesn't seem to have any data. Is it known when performance with WebRender will also be tracked?

EDIT:
I just realized that the problem is that all the benchmark results have the value '1'.

[1] https://arewefastyet.com/#machine=36&view=breakdown&suite=motionmark

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.

MotionMark is now properly integrated in the testing suite.
