### ISSUE TITLE
Chart deeplinks don't always show the same data as in the session that created them

### ISSUE THREAD

**Issue by tschneidereit** [mozilla/arewefastyet#27]
An example is [this deeplink](http://arewefastyet.com/#machine=11&view=single&suite=ss&subtest=validate-input&start=1404923215&end=1405560809), which I created by zooming in on the `ss-validate-input` chart until I got roughly the span between July 9th and July 16th. In my original session, each entry was for a single revision. When clicking on the link, the visual result is identical, but the entries link to revision ranges.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
