### ISSUE TITLE
Create run.py that works the same as driver/run.sh

### ISSUE THREAD

**Issue by h4writer** [mozilla/arewefastyet#54]
We need a place that understands the task the command and control unit sends. This new file will eventually requests new tasks online and run "dostuff.py" with the correct settings.

So step 1 is to create "run.py" that does exactly the same as "driver/run.sh".

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
