### ISSUE TITLE
Command and control unit (website) should send what should get run.

### ISSUE THREAD

**Issue by h4writer** [mozilla/arewefastyet#56]
This is part 3. Now we have already build_XXX.py that just run what asked and have run.py deciding which revisions to run.

Now we want to move that logic to the website. Run.py will request for a task to the website (which gives the revision + which benchmark should get run). Run.py will translate that request and run dostuff.py with the correct flags/config files.

So the logic in run.py need to get moved to the website which will command the slaves.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
