### ISSUE TITLE
Make it possible to view non-aggregated graphs

### ISSUE THREAD

**Issue by h4writer** [mozilla/arewefastyet#57]
Currently when visiting AWFY an aggregated graph will get shown. Where on the left side historical data is shown and on the right side the last X datapoints.

This was a compromise since some people wanted historic data, others only need the newest datapoints. As a result both were added in one graph.

Now sometimes it would be good to show only newest or only historic data.
This bug is to add a setting that makes it possible to switch between those views.

This is a good first bug. Though when somebody wants to start this. Please let me know. I can give more details on what should happen exactly.

**Comment by subhdeep** [comment]
i would really like to work on this. what all details should i go through.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
