### ISSUE TITLE
Consider using piwik rather than google analytics

### ISSUE THREAD

**Issue by bnjbvr** [mozilla/arewefastyet#73]
Piwik is free open-source software, written in PHP. It's the best open-source solution for analytics and it has a really nice privacy policy (in particular, it obfuscates visitors personal info, when this info could help uniquely identify them). Could we use this rather than GAnalytics?

**Comment by h4writer** [comment]
Thanks for the suggestion. I didn't know piwik at all. Currently try-running it on arewefastyet. Install was painless.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/mozilla/arewefastyet/commit/a8428f9d0624f3af12b860fd7250634700912e7b .
