### ISSUE TITLE
Use github mirrors to display differences between sha1

### ISSUE THREAD

**Issue by nbp** [mozilla/arewefastyet#74]
The flame slaves are reporting the git sha1 when the mapfile which is used to convert the sha1 into change set fails to be updated. ( https://bugzilla.mozilla.org/show_bug.cgi?id=1175106 )

Would it be possible to use github as a fallback when no changeset are available, and that the git-sha1 is provided instead.

https://github.com/mozilla/gecko-dev/compare/6ad3c672b555bc122088f7ea6364c2d2fb197499...d9cd08181eec8a03b4b19a6919338c97aea64a4e

instead of

http://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=git-6ad3c672b555bc122088f7ea6364c2d2fb197499&tochange=git-d9cd08181eec8a03b4b19a6919338c97aea64a4e

**Comment by nbp** [comment]
This is no longer a priority since I fixed this issue in https://github.com/nbp/arewefastyet/commit/d18295871005adaa0530a61cb01cb6cd39f84a11

**Comment by h4writer** [comment]
I think this can get closed, since we now have "extra info" on a submit?

**Comment by nbp** [comment]
Are you suggesting that the link should be part of the extra info?

**Comment by h4writer** [comment]
Don't you already provide the git sha1 through the extra info?

**Comment by nbp** [comment]
No, the extra info only prints the current revision sha1.  The extra info makes forging links by hand way easier, but I still have to forge the links, instead of having an automated way form the previous commit and the new commit.

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
