### ISSUE TITLE
Test if octane.localhost etc work and add documentation to get it working

### ISSUE THREAD

**Issue by h4writer** [mozilla/arewefastyet#79]
People need to adjust their /etc/hosts file in order to run the browser benchmarks.
Test if that actually has been done before running the benchmarks and give
instructions on how to add them!

**Comment by dhananjay92** [comment]
This is the exact problem I was facing too. I modified the AWFY to run remote dromaeo, but it never  did anything on `python execute.py -b remote.dromaeo`. After a bit of debugging I found it was not able to reach `dromaeo.localhost:8888/` at all!

**Comment by bnjbvr** [comment]
Hey @dhananjay92, any intent to create a pull request with your commit? That'd be greatly appreciated :+1:

**Comment by dhananjay92** [comment]
That's already done: #82

**Comment by bnjbvr** [comment]
Cool, thanks!
