### ISSUE TITLE
Chromium asks for "chromium safe storage" which breaks running

### ISSUE THREAD

**Issue by h4writer** [mozilla/arewefastyet#94]
During one of the tests it asks for the "chromium safe storage" to use your keychain. This creates a popup that blocks the whole browser from running next benchmarks:

I assume this is caused by one of the following benchmarks
Unity WebGL
Web Audio

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
